version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "{{ cookiecutter.python_version }}"

sphinx:
  fail_on_warning: false

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .